version: '3.9'

services:
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./app/.env

  web:
    build: .
    command: /docker-entrypoint.sh
    ports:
      - 80:8000
    volumes:
      - ./app/:/home/app/web/
    env_file:
      - ./app/.env
    depends_on:
      - db

volumes:
  postgres_data:
